In [1]:
#Import Pandas and read csv file
import pandas as pd
import numpy as np
df = pd.read_csv("Business_Licenses.csv")
df.head()

/Users/gallasteguicrino/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (9,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,...,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION
0,22308-20060816,1723393,29481,1,BELL OIL TERMINAL INC,Bell Oil Terminal LLC,3741 S PULASKI RD 1,CHICAGO,IL,60623,...,08/16/2006,08/15/2007,08/10/2006,08/11/2006,AAI,NaN,NaN,41.825320,-87.723960,"(41.82531992987547, -87.72395999659746)"
1,1620668-20160516,2455262,295026,1,BUCCI BIG & TALL INC.,BUCCI BIG & TALL INC.,558 W ROOSEVELT RD,CHICAGO,IL,60607,...,05/16/2016,05/15/2018,05/18/2016,08/30/2016,AAI,NaN,NaN,41.867339,-87.641590,"(41.86733856638269, -87.64159005699716)"
2,2368602-20160616,2460909,291461,3,"PROJECT: VISION , INC.","PROJECT : VISION , INC",2301 S ARCHER AVE 1 1,CHICAGO,IL,60616,...,06/16/2016,06/15/2017,06/21/2016,06/22/2016,AAC,08/30/2016,NaN,41.850843,-87.638734,"(41.85084294374687, -87.63873424399071)"
3,2060891-20141016,2353257,357247,1,FOLASHADE'S CLEANING SERVICE INC.,FOLASHADE'S CLEANING SERVICE INC.,1965 BERNICE RD 1 1SW,LANSING,IL,60438,...,10/16/2014,10/15/2016,04/01/2016,04/01/2016,AAI,NaN,38.0,41.951316,-87.678586,"(41.95131555606832, -87.67858578019546)"
4,1144216-20070516,1804790,147,63,WALGREEN CO.,Walgreens # 05192,9148 S COMMERCIAL AVE 1ST,CHICAGO,IL,60617,...,05/16/2007,05/15/2008,05/10/2007,05/11/2007,AAI,NaN,5.0,41.728622,-87.551366,"(41.72862173556932, -87.55136646594693)"

In [2]:
df.shape

(957634, 34)

In [3]:
# List all variables as some were omited above. 
list(df)

['ID',
 'LICENSE ID',
 'ACCOUNT NUMBER',
 'SITE NUMBER',
 'LEGAL NAME',
 'DOING BUSINESS AS NAME',
 'ADDRESS',
 'CITY',
 'STATE',
 'ZIP CODE',
 'WARD',
 'PRECINCT',
 'WARD PRECINCT',
 'POLICE DISTRICT',
 'LICENSE CODE',
 'LICENSE DESCRIPTION',
 'BUSINESS ACTIVITY ID',
 'BUSINESS ACTIVITY',
 'LICENSE NUMBER',
 'APPLICATION TYPE',
 'APPLICATION CREATED DATE',
 'APPLICATION REQUIREMENTS COMPLETE',
 'PAYMENT DATE',
 'CONDITIONAL APPROVAL',
 'LICENSE TERM START DATE',
 'LICENSE TERM EXPIRATION DATE',
 'LICENSE APPROVED FOR ISSUANCE',
 'DATE ISSUED',
 'LICENSE STATUS',
 'LICENSE STATUS CHANGE DATE',
 'SSA',
 'LATITUDE',
 'LONGITUDE',
 'LOCATION']

In [4]:
# Create new dataframe with the variables we'll use. 
df_1 = df[["LEGAL NAME", 'DOING BUSINESS AS NAME', "LICENSE CODE", "CITY", "WARD", "ZIP CODE", "DATE ISSUED", "LATITUDE", "LONGITUDE"]]
df_1.head()

,LEGAL NAME,DOING BUSINESS AS NAME,LICENSE CODE,CITY,WARD,ZIP CODE,DATE ISSUED,LATITUDE,LONGITUDE
0,BELL OIL TERMINAL INC,Bell Oil Terminal LLC,1010,CHICAGO,14.0,60623,08/11/2006,41.825320,-87.723960
1,BUCCI BIG & TALL INC.,BUCCI BIG & TALL INC.,1010,CHICAGO,25.0,60607,08/30/2016,41.867339,-87.641590
2,"PROJECT: VISION , INC.","PROJECT : VISION , INC",1625,CHICAGO,25.0,60616,06/22/2016,41.850843,-87.638734
3,FOLASHADE'S CLEANING SERVICE INC.,FOLASHADE'S CLEANING SERVICE INC.,1010,LANSING,NaN,60438,04/01/2016,41.951316,-87.678586
4,WALGREEN CO.,Walgreens # 05192,1010,CHICAGO,10.0,60617,05/11/2007,41.728622,-87.551366

In [5]:
# Flter by city (Chicago) 
df_2 = df_1.query('CITY == "CHICAGO"')
df_2.head()

,LEGAL NAME,DOING BUSINESS AS NAME,LICENSE CODE,CITY,WARD,ZIP CODE,DATE ISSUED,LATITUDE,LONGITUDE
0,BELL OIL TERMINAL INC,Bell Oil Terminal LLC,1010,CHICAGO,14.0,60623,08/11/2006,41.825320,-87.723960
1,BUCCI BIG & TALL INC.,BUCCI BIG & TALL INC.,1010,CHICAGO,25.0,60607,08/30/2016,41.867339,-87.641590
2,"PROJECT: VISION , INC.","PROJECT : VISION , INC",1625,CHICAGO,25.0,60616,06/22/2016,41.850843,-87.638734
4,WALGREEN CO.,Walgreens # 05192,1010,CHICAGO,10.0,60617,05/11/2007,41.728622,-87.551366
5,"BURKS HEATING AND COOLING SOLUTIONS, LLC","BURKS HEATING AND COOLING SOLUTIONS, LLC",4404,CHICAGO,15.0,60636,08/30/2016,41.789617,-87.669472

In [6]:
#Remaining rows
df_2.shape

(887891, 9)

In [7]:
# Filter by license code
df_3 = df_2[df_2['LICENSE CODE'] == 1006]

#Reamining rows
df_3.shape

(141713, 9)

In [8]:
#Print head 
df_3.head(50)

,LEGAL NAME,DOING BUSINESS AS NAME,LICENSE CODE,CITY,WARD,ZIP CODE,DATE ISSUED,LATITUDE,LONGITUDE
11,"OLD TOWN OIL, LLC","OLD TOWN OIL, LLC",1006,CHICAGO,27.0,60610,08/30/2016,41.910408,-87.634540
35,MO MO HOUSE CORP.,NEPAL HOUSE - NAPALESE CUISINE,1006,CHICAGO,50.0,60659,08/30/2016,41.997535,-87.694822
44,THIRD DEGREE CHICAGO LLC,STUDIO III,1006,CHICAGO,42.0,60654,01/17/2017,NaN,NaN
47,"VIENNA SERVICES, INC.",CAFE VIENNA,1006,CHICAGO,43.0,60614,08/31/2016,41.928487,-87.642044
63,STARBUCKS CORPORATION,STARBUCKS COFFEE #216,1006,CHICAGO,42.0,60611,03/18/2015,41.893341,-87.617589
92,GENERAL GROWTH MANAGEMENT INC.,GENERAL GROWTH MANAGEMENT INC,1006,CHICAGO,42.0,60606,08/31/2016,41.883498,-87.637200
107,STARBUCKS CORPORATION,STARBUCKS COFFEE #9426,1006,CHICAGO,1.0,60642,03/18/2015,41.891770,-87.658605
108,STARBUCKS CORPORATION,STARBUCKS COFFEE #2510,1006,CHICAGO,42.0,60610,03/18/2015,41.889683,-87.637121
111,KURIAN FOODS INC.,AL'S BEEF,1006,CHICAGO,42.0,60604,08/31/2016,41.878674,-87.626242
131,STARBUCKS CORPORATION,STARBUCKS #17743,1006,CHICAGO,40.0,60659,03/18/2015,41.992587,-87.689862
141,FG TRADING INC.,24 SEVEN FOOD MART,1006,CHICAGO,46.0,60613,08/31/2016,41.961667,-87.649761
218,"SRJ ENTERPRISES, INC.",7-ELEVEN,1006,CHICAGO,42.0,60606,08/31/2016,41.879473,-87.635807
224,"ROXANNE FOOD MART, INC.","ROXANNE FOOD MART, INC.",1006,CHICAGO,20.0,60621,08/31/2016,41.792483,-87.644966
227,THOMAS I. YI,"HOUND DOG, BURGER & TERIYAKI RESTAURANT",1006,CHICAGO,26.0,60612,08/31/2016,41.890595,-87.684048
237,LUFRAN INC,PEPE'S MEXICAN RESTAURANT,1006,CHICAGO,6.0,60619,08/31/2016,41.750921,-87.619937
244,STARBUCKS CORPORATION,STARBUCKS COFFEE #22949,1006,CHICAGO,42.0,60604,05/15/2012,41.885802,-87.624660
245,STARBUCKS CORPORATION,STARBUCKS COFFEE #15683,1006,CHICAGO,42.0,60602,03/18/2015,41.882288,-87.624518
311,"Food For Thought Cafe at the Adler, Ltd.",Galileo's,1006,CHICAGO,4.0,60605,08/31/2016,41.865732,-87.619669
323,"MINA 4 ENTERPRISE GROUP INC.,",7-ELEVEN #33496C,1006,CHICAGO,4.0,60605,08/31/2016,41.875011,-87.627475
348,"LOYOLA FOOD MART, INC.","LOYOLA FOOD MART, INC.",1006,CHICAGO,49.0,60626,08/31/2016,42.000720,-87.660656
366,"CANALU, LLC",DINOTTO PIZZERIA (CATERING),1006,CHICAGO,27.0,60610,08/31/2016,41.910627,-87.634547
402,"GO! GROCER PINE GROVE, INC.",GO! GROCER,1006,CHICAGO,46.0,60613,08/31/2016,41.953774,-87.648061
410,"LA TERRAZA GALLO CORP.,",LA TERRAZA GALLO,1006,CHICAGO,12.0,60623,08/31/2016,41.851745,-87.698823
442,LA MICHOACANA DE PONCITLAN INC.,LA MICHOACANA DE PONCITLAN,1006,CHICAGO,14.0,60632,08/31/2016,41.799082,-87.703863
498,"HEALTHY ORGANIC KIDS, INC.",HEALTHY ORGANIC KIDS,1006,CHICAGO,27.0,60642,08/31/2016,41.891026,-87.652005
548,YUN CHIU YU,CHINA SNACK,1006,CHICAGO,12.0,60623,07/19/2004,41.851709,-87.701519
595,"LA BAGUETTE NORTH, INC.",LA BAGUETTE NORTH,1006,CHICAGO,49.0,60626,11/18/2003,42.009193,-87.673860
596,PESTO 59 INC.,AVALON BAR & GRILL,1006,CHICAGO,41.0,60656,08/31/2016,41.977955,-87.846320
648,STARBUCKS CORPORATION,Starbucks Coffee #22423,1006,CHICAGO,2.0,60610,03/18/2015,41.904831,-87.635028
655,"DARIA EXPORTS, INC.",TARBOUSH MEDITERRANEAN GRILL,1006,CHICAGO,32.0,60622,08/31/2016,41.910734,-87.668093
678,1700 DIVISION OPERATING LLC,CARRIAGE HOUSE,1006,CHICAGO,1.0,60622,08/31/2016,41.903407,-87.670466
704,MARY'S BAR B QUE INC. File,MARY'S BAR B QUE INC.,1006,CHICAGO,24.0,60624,08/31/2016,41.873269,-87.725555
739,"FRENCHYCAKE, LLC",LE CAFE,1006,CHICAGO,47.0,60625,08/31/2016,41.966413,-87.686937
930,TAQUERIA EL BURRITO FELIZ INC,TAQUERIA EL BURRITO FELIZ INC,1006,CHICAGO,16.0,60629,11/03/2004,41.779195,-87.695433
934,HUAMAO RESTAURANT INC.,HUAMAO RESTAURANT INC.,1006,CHICAGO,28.0,60607,08/31/2016,41.869195,-87.663781
959,ROTI 10 SOUTH RIVERSIDE LLC,ROTI,1006,CHICAGO,42.0,60606,09/01/2016,41.881664,-87.638887
970,ALLIED INTERNATIONAL INC.,NEW SUPREME FISH STEAK & HOAGIE,1006,CHICAGO,20.0,60609,10/29/2009,41.794398,-87.645310
975,PRESENCE CHICAGO HOSPITALS NETWORK,PRESENCE SAINT JOSEPH HOSPITAL - CHICAGO,1006,CHICAGO,44.0,60657,02/13/2015,41.934403,-87.636806
980,PRESENCE CHICAGO HOSPITALS NETWORK,PRESENCE ST. MARY OF NAZARETH HOSPITAL,1006,CHICAGO,2.0,60622,11/17/2010,41.902972,-87.683485
987,PRESENCE CHICAGO HOSPITALS NETWORK,PRESENCE ST. MARY OF NAZARETH HOSPITAL,1006,CHICAGO,2.0,60622,11/14/2008,41.902972,-87.683485
989,"ROTI 300 WEST ADAMS, LLC",ROTI MEDITERRANEAN GRILL,1006,CHICAGO,42.0,60606,09/01/2016,41.879476,-87.635587
997,MARTHA M GARCIA-HERNANDEZ,EL TACO AZTECA,1006,CHICAGO,25.0,60608,09/01/2016,41.851995,-87.680313
1001,"KAGIZA, INC.",NINEFACE THAI & SUSHI BAR,1006,CHICAGO,46.0,60613,11/13/2012,41.953032,-87.654355
1004,"MADELINE KHAN, LTD.",VINCENT,1006,CHICAGO,48.0,60640,08/06/2013,41.979744,-87.667738
1008,SAM'S CUT RATE FOOD & LIQ INC,SAM'S CUT RATE FOOD & LIQ INC,1006,CHICAGO,6.0,60619,09/01/2016,41.758563,-87.612618
1010,PRESENCE CHICAGO HOSPITALS NETWORK,PRESENCE ST. MARY OF NAZARETH HOSPITAL,1006,CHICAGO,2.0,60622,12/07/2005,41.902972,-87.683485
1012,67TH WENTWORTH FOODS INC.,67TH WENTWORTH SHELL,1006,CHICAGO,6.0,60621,09/01/2016,41.772809,-87.629820
1029,PRESENCE CHICAGO HOSPITALS NETWORK,PRESENCE SAINT ELIZABETH HOSPITAL,1006,CHICAGO,1.0,60622,11/18/2003,41.907609,-87.687002
1036,"MADELINE KHAN, LTD.",VINCENT,1006,CHICAGO,48.0,60640,07/22/2009,41.979744,-87.667738
1038,PRESENCE CHICAGO HOSPITALS NETWORK,PRESENCE RESURRECTION MEDICAL CENTER,1006,CHICAGO,41.0,60631,08/11/2004,41.988575,-87.812978

In [9]:
# Drop missing data
df_4 = df_3.dropna()

#Remaining rows
df_4.shape

(140454, 9)

In [10]:
# Print head
df_4 = df_4.reset_index(drop=True)
df_4.head()

,LEGAL NAME,DOING BUSINESS AS NAME,LICENSE CODE,CITY,WARD,ZIP CODE,DATE ISSUED,LATITUDE,LONGITUDE
0,"OLD TOWN OIL, LLC","OLD TOWN OIL, LLC",1006,CHICAGO,27.0,60610,08/30/2016,41.910408,-87.634540
1,MO MO HOUSE CORP.,NEPAL HOUSE - NAPALESE CUISINE,1006,CHICAGO,50.0,60659,08/30/2016,41.997535,-87.694822
2,"VIENNA SERVICES, INC.",CAFE VIENNA,1006,CHICAGO,43.0,60614,08/31/2016,41.928487,-87.642044
3,STARBUCKS CORPORATION,STARBUCKS COFFEE #216,1006,CHICAGO,42.0,60611,03/18/2015,41.893341,-87.617589
4,GENERAL GROWTH MANAGEMENT INC.,GENERAL GROWTH MANAGEMENT INC,1006,CHICAGO,42.0,60606,08/31/2016,41.883498,-87.637200

In [11]:
# Save clean dataset into a CSV file. 
df_4.to_csv('Clean_Chicago_Restaurants_Licenses.csv')